import { readFileSync, writeFileSync } from "fs";
import https from "https";

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
const MAX_FILE_SIZE = 50000; // 50KB per file limit

async function callOpenRouter(messages) {
  const data = JSON.stringify({
    model: "anthropic/claude-sonnet-4-20250514",
    messages: messages,
    max_tokens: 2000,
    temperature: 0.3,
  });

  const options = {
    hostname: "openrouter.ai",
    path: "/api/v1/chat/completions",
    method: "POST",
    headers: {
      Authorization: `Bearer ${OPENROUTER_API_KEY}`,
      "Content-Type": "application/json",
      "Content-Length": data.length,
      "HTTP-Referer": "https://github.com/Vedant1607/AI-Code-Reviewer",
      "X-Title": "AI Code Reviewer",
    },
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let body = "";
      res.on("data", (chunk) => (body += chunk));
      res.on("end", () => {
        try {
          const response = JSON.parse(body);
          resolve(response.choices[0].message.content);
        } catch (error) {
          reject(error);
        }
      });
    });

    req.on("error", reject);
    req.write(data);
    req.end();
  });
}

async function reviewFiles(changedFiles) {
  const files = changedFiles.split(",").filter((f) => f.trim());

  if (files.length === 0) {
    console.log("No files to review");
    return "✅ No code changes detected to review.";
  }

  let reviewMarkdown = `## 🤖 AI Code Review\n\n`;
  reviewMarkdown += `**Files reviewed:** ${files.length}\n\n`;

  for (const file of files) {
    try {
      const content = readFileSync(file, "utf8");

      if (content.length > MAX_FILE_SIZE) {
        reviewMarkdown += `### 📄 \`${file}\`\n⚠️ File too large to review (${content.length} chars)\n\n`;
        continue;
      }

      console.log(`Reviewing ${file}...`);

      const systemPrompt = `You are a senior code reviewer. Analyze the code and provide:
1. **Security Issues** (if any)
2. **Performance Concerns** (if any)
3. **Code Quality & Best Practices**
4. **Positive Aspects** (what's done well)

Be concise but thorough. Use markdown formatting. If the code is good, say so!`;

      const userPrompt = `Review this code from \`${file}\`:\n\n\`\`\`\n${content}\n\`\`\``;

      const review = await callOpenRouter([
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ]);

      reviewMarkdown += `### 📄 \`${file}\`\n\n${review.choices[0].message.content}\n\n---\n\n`;

      // Rate limiting
      await new Promise((resolve) => setTimeout(resolve, 1000));
    } catch (error) {
      console.error(`Error reviewing ${file}:`, error);
      reviewMarkdown += `### 📄 \`${file}\`\n❌ Error reviewing file: ${error.message}\n\n`;
    }
  }

  reviewMarkdown += `\n*Generated by [AI Code Reviewer](https://github.com/Vedant1607/AI-Code-Reviewer) powered by OpenRouter*`;

  return reviewMarkdown;
}

// Main execution
const changedFiles = process.argv[2] || "";
reviewFiles(changedFiles)
  .then((review) => {
    writeFileSync("/tmp/ai-review.md", review);
    console.log("Review completed successfully!");
    console.log(review);
  })
  .catch((error) => {
    console.error("Review failed:", error);
    process.exit(1);
  });
